### ISSUE TITLE
wiki cela sert a quoi ?

### ISSUE THREAD

**Issue by Noxhero** [Noxhero/Projet#4]
Chaque dépôt sur GitHub.com est équipé d'une section pour l'hébergement de la documentation, appelée wiki. Vous pouvez utiliser le wiki de votre dépôt afin de partager du contenu détaillé sur votre projet, par exemple pour décrire son utilisation, sa conception ou ses principes de base.

**Comment by RaphaelJ19** [comment]
L'onglet Wiki sur GitHub est une fonctionnalité qui permet aux utilisateurs d'un dépôt (repository) de créer et de gérer de la documentation, ou des pages d'information, directement dans le dépôt. Cet onglet est souvent utilisé pour stocker des informations telles que :

Documentation du projet : Une explication détaillée du projet, des objectifs, et des fonctionnalités.
Guides d'utilisation : Des instructions sur la manière d'installer, configurer, et utiliser le projet.
Contributions : Des règles ou des conseils sur la manière de contribuer au projet.
Historique et changements : Des informations sur l'évolution du projet ou les changements majeurs.
Notes de version : Des résumés des nouvelles versions et des améliorations.
Le Wiki est versionné (comme le code source dans le dépôt), ce qui signifie que chaque modification est enregistrée et qu'il est possible de revenir à une version antérieure.

Les utilisateurs peuvent organiser le contenu sous forme de pages, créer des sous-sections, et lier entre elles les différentes pages, ce qui en fait un outil utile pour maintenir la documentation vivante et accessible à toute l'équipe.

**Comment by RaphaelJ19** [comment]
L'onglet Wiki sur GitHub est une fonctionnalité qui permet aux utilisateurs d'un dépôt (repository) de créer et de gérer de la documentation, ou des pages d'information, directement dans le dépôt. Cet onglet est souvent utilisé pour stocker des informations telles que :

Documentation du projet : Une explication détaillée du projet, des objectifs, et des fonctionnalités.
Guides d'utilisation : Des instructions sur la manière d'installer, configurer, et utiliser le projet.
Contributions : Des règles ou des conseils sur la manière de contribuer au projet.
Historique et changements : Des informations sur l'évolution du projet ou les changements majeurs.
Notes de version : Des résumés des nouvelles versions et des améliorations.
Le Wiki est versionné (comme le code source dans le dépôt), ce qui signifie que chaque modification est enregistrée et qu'il est possible de revenir à une version antérieure.

Les utilisateurs peuvent organiser le contenu sous forme de pages, créer des sous-sections, et lier entre elles les différentes pages, ce qui en fait un outil utile pour maintenir la documentation vivante et accessible à toute l'équipe.
